version: '3.2'
services:
    kepler:
        image: ewout/kepler:latest
        restart: always
        environment:
            MYSQL_HOST: mariadb
            MYSQL_USER: kepler
            MYSQL_DATABASE: kepler
            MYSQL_PASSWORD: verysecret
        depends_on:
            - redis
            - mariadb
        links:
            - mariadb
            - redis
        ports:
            - "12321:12321"
        expose:
            - "12321"
            - "12309"

    matcha:
        image: ewout/matcha:latest
        depends_on:
            - redis
        links:
            - redis
            - kepler
        restart: always
        environment:
            - REDIS_HOST=redis
            - REDIS_PORT=6379

    nginx:
        image: nginx:mainline
        restart: always
        ports:
            - "12316:80"
        volumes:
            - ./public:/srv/http/matcha/public:ro
            - ./app:/srv/http/matcha/app:ro
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - ./h5bp/h5bp:/etc/nginx/h5bp:ro
            - ./h5bp/mime.types:/etc/nginx/mime.types:ro

    redis:
        image: redis:latest
        restart: always

    mariadb:
        image: mariadb:10.2.15
        restart: always
        ports:
           - "3307:3306"
        environment:
            MYSQL_ROOT_PASSWORD: superverysecret
            MYSQL_DATABASE: kepler
            MYSQL_USER: kepler
            MYSQL_PASSWORD: verysecret
        volumes:
            - ./kepler/kepler.sql:/docker-entrypoint-initdb.d/kepler.sql
            - ./site.sql:/docker-entrypoint-initdb.d/site.sql
